import { DemoObject } from "./types";

// Demo project data
export const DEMO_ITEMS: DemoObject[] = [
  {
    id: "sort-algorithm-visualizer",
    title: "Sort Algorithm Visualizer",
    description: "A web app to visualize sorting algorithms; part of my fundamentals series.",
    site: "generic",
    url: "https://sort-algorithms-three.vercel.app/",
    sourceUrl: "https://github.com/Williamlowr/sort-algorithms",
    tags: ["react", "sorts", "algorithms", "fundamentals", "javascript"],
  },
  {
    id: "race-my-WPM",
    title: "Race My WPM",
    description: "An interactive typing game that lets you attempt to race a pre-recorded session of my own WPM recorded using my Typing Recorder tool. Built with React and Tailwind. Can you type faster than me?",
    site: "generic",
    url: "https://race-my-typing.vercel.app/",
    sourceUrl: "https://github.com/Williamlowr/race-my-typing",
    tags: ["react", "games", "typing", "tailwind", "javascript"],
  },
  {
    id: "web-gl-demo",
    title: "Shadow Room (WebGL)",
    description: "This is a complex WebGL demo that uses graphics programming to render a 3D room with dynamic shadows based on a moving light source. It showcases advanced techniques in WebGL including shaders, lighting models, and transformation matrices. There are interactable controls to control/move the light source and toggle cube rotation or lighting.",
    site: "generic",
    url: "https://web-gl-demo-alpha.vercel.app/",
    sourceUrl: "https://github.com/Williamlowr/WebGL-Demo",
    tags: ["games", "interactable", "graphics", "webgl", "shaders", "lighting", "3d"],
  },
  {
    id: "city-temperature-search",
    title: "Global Temperature Search",
    description: "This simple tool retrieves the minimum and maximum temperatures matching your criteria. Data Set is a huge CSV containing global temperatures between the years 1995 and 2020, often used for programming learning. I originally navigated and searched the files using java, but I rewrote the searching as a node API; original java files are included for demo purposes.",
    site: "generic",
    url: "https://city-temperature-search-sigma.vercel.app/",
    sourceUrl: "https://github.com/Williamlowr/city-temperature-search",
    tags: ["java", "fundamentals", "api", "tools", "data handling"],
  },
  {
    id: "client-server-frontend",
    title: "TCP Server Demo",
    description: "This is a simple demo of a TCP client-server application; the server is built using Java and was Dockerized and deployed on Railway (the code for the backend is also available in projects). User uploads a file and the server checks and returns the file size and SHA-256 Hash. The simple next.js frontend will compare the hash of the uploaded file to ensure integrity during transfer.",
    site: "generic",
    url: "https://client-server-frontend-gilt.vercel.app/",
    sourceUrl: "https://github.com/Williamlowr/client-server-frontend",
    tags: ["next.js", "fundamentals", "server", "tcp", "data handling", "sha256", "docker", "java"],
  },
  {
    id: "Typing-Recorder-JSON",
    title: "Typing Recorder (JSON)",
    description: "A small dev tool I made to record your typing inputs and export them as a JSON file with timestamps; done to practice using Python and TKinter GUI. You can click the embed to see a quick video demo, or visit the repository to download the Python script/bundled executable (verified safe with an attached virus check).",
    site: "generic",
    url: "https://github.com/Williamlowr/Typing-Recorder-JSON",
    sourceUrl: "https://github.com/Williamlowr/Typing-Recorder-JSON",
    tags: ["python", "tkinter", "json", "tools"],
  },
  // {
  //   id: "ui-codepen",
  //   title: "CSS Cards (CodePen)",
  //   description: "Responsive card layout pen.",
  //   site: "codepen",
  //   url: "https://codepen.io/team/codepen/pen/PNaGbb",
  //   tags: ["css", "layout"],
  // },
  // {
  //   id: "obs-notebook",
  //   title: "Observable Notebook",
  //   site: "observable",
  //   url: "https://observablehq.com/@observablehq/plot-introduction",
  //   tags: ["data-visualization", "notebook"],
  // },
];
