import { DemoObject } from "./types";

// Demo project data
export const DEMO_ITEMS: DemoObject[] = [
  {
    id: "sort-algorithm-visualizer",
    featured: false,
    rank: 4,
    title: "Sort Algorithm Visualizer",
    description: "Interactive visualizations of common sorting algorithms, built to reinforce algorithmic fundamentals.",
    site: "generic",
    url: "https://sort-algorithms-three.vercel.app/",
    sourceUrl: "https://github.com/Williamlowr/sort-algorithms",
    tags: ["react", "javascript", "frontend", "algorithms"],
  },
  {
    id: "race-my-WPM",
    featured: false,
    rank: 1,
    title: "Race My WPM",
    description: "A competitive typing game that lets users race against a recorded high-WPM session in real time.",
    site: "generic",
    url: "https://race-my-typing.vercel.app/",
    sourceUrl: "https://github.com/Williamlowr/race-my-typing",
    tags: ["react", "javascript", "frontend", "games"],
  },
  {
    id: "web-gl-demo",
    featured: false,
    rank: 2,
    title: "Shadow Room (WebGL)",
    description: "A 3D WebGL demo featuring real-time lighting, shaders, and interactive scene controls.",
    site: "generic",
    url: "https://web-gl-demo-alpha.vercel.app/",
    sourceUrl: "https://github.com/Williamlowr/WebGL-Demo",
    tags: ["javascript", "frontend", "graphics"],
  },
  {
    id: "city-temperature-search",
    featured: false,
    rank: 6,
    title: "Global Temperature Search",
    description: "Searches large historical temperature datasets via a Node API, rewritten from an original Java implementation.",
    site: "generic",
    url: "https://city-temperature-search-sigma.vercel.app/",
    sourceUrl: "https://github.com/Williamlowr/city-temperature-search",
    tags: ["backend", "data", "java", "javascript"],
  },
  {
    id: "client-server-frontend",
    featured: false,
    rank: 5,
    title: "TCP Server Demo",
    description: "A Java TCP server with SHA-256 file verification, paired with a lightweight Next.js frontend.",
    site: "generic",
    url: "https://client-server-frontend-gilt.vercel.app/",
    sourceUrl: "https://github.com/Williamlowr/client-server-frontend",
    tags: ["nextjs", "java", "backend", "docker"],
  },
  {
    id: "lawyer-template",
    featured: false,
    rank: 3,
    title: "Law Firm Template",
    description: "A responsive React template designed as a starting point for small-business client sites.",
    site: "generic",
    url: "https://lawyer-template-nine.vercel.app/",
    sourceUrl: "https://github.com/Williamlowr/lawyer-template",
    tags: ["react", "javascript", "frontend"],
  },
  {
    id: "Typing-Recorder-JSON",
    featured: false,
    rank: 7,
    title: "Typing Recorder (JSON)",
    description: "A Python desktop tool that records keystrokes with timestamps and exports structured JSON data.",
    site: "generic",
    url: "https://www.loom.com/embed/432aa4ca8a94424e9b34a5b16f46bf59",
    sourceUrl: "https://github.com/Williamlowr/Typing-Recorder-JSON",
    tags: ["python", "tools", "data"],
  },
  // {
  //   id: "ui-codepen",
  //   title: "CSS Cards (CodePen)",
  //   description: "Responsive card layout pen.",
  //   site: "codepen",
  //   url: "https://codepen.io/team/codepen/pen/PNaGbb",
  //   tags: ["css", "layout"],
  // },
  // {
  //   id: "obs-notebook",
  //   title: "Observable Notebook",
  //   site: "observable",
  //   url: "https://observablehq.com/@observablehq/plot-introduction",
  //   tags: ["data-visualization", "notebook"],
  // },
];
